# Generated by Django 3.0.4 on 2020-03-28 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tabletennis', '0002_auto_20200321_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner_score', models.IntegerField(help_text='Score of the winning player')),
                ('loser_score', models.IntegerField(help_text='Score of the losing player')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('loser', models.ForeignKey(help_text='Losing player', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_lost', to='tabletennis.Player')),
                ('winner', models.ForeignKey(help_text='Winning player', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_won', to='tabletennis.Player')),
            ],
        ),
    ]
