# Generated by Django 3.0.4 on 2020-05-04 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabletennis', '0004_auto_20200403_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='loser_score',
            field=models.IntegerField(help_text='Score of the losing player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='winner_score',
            field=models.IntegerField(help_text='Score of the winning player'),
        ),
    ]
